source 'https://rubygems.org' do
  gem 'minitest'
  gem 'sinatra'
  gem 'twitter'
  gem 'thin'
  gem 'cucumber'
  gem 'rufus-scheduler'
  gem 'omniauth-twitter'
  gem 'sqlite3'
  gem 'sinatra-contrib'
  gem 'capybara'
  gem 'rspec'
  gem 'simplecov'
  gem 'capybara-screenshot'
  gem 'selenium-webdriver'
  gem 'puma'
end