#All gem requirements
require 'erb'
require 'sinatra'
require 'twitter'
require 'rufus-scheduler'
require 'omniauth-twitter'
require 'sqlite3'
require_relative 'addJourney.rb'
require_relative 'addTaxi.rb'
require_relative 'addUser.rb'
require_relative 'addComplaint.rb'
require_relative 'dashboard.rb'
require_relative 'main.rb'
require_relative 'login.rb'
require_relative 'complaint.rb'
require_relative 'marketing.rb'
